version: "3"

networks:
  app-tier:
    driver: bridge

services:
  memgraph-mage:
    build: ./memgraph
    ports:
      - "7687:7687"
    environment:
      PULSAR_IP: pulsar
      PULSAR_PORT: "6650"
    entrypoint:
      [
        "/usr/lib/memgraph/memgraph",
        "--telemetry-enabled=false",
        "--query-modules-directory=/procedures,/transformations,/usr/lib/memgraph/query_modules",
        "--log-level=TRACE",
      ]
    networks:
      - app-tier

  pulsar:
    image: apachepulsar/pulsar:2.6.0
    ports:
      - 8080:8080
      - 6650:6650
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: bin/pulsar standalone
    networks:
      - app-tier

  core:
    image: tianon/true
    restart: "no"
    depends_on:
      - pulsar
      - memgraph-mage

  stream:
    build:
      context: ./
      dockerfile: ./stream/Dockerfile
    entrypoint: ["python3", "produce.py", "--stream-delay", "2.0"]
    environment:
      PULSAR_IP: pulsar
      PULSAR_PORT: 6650
      PULSAR_TOPIC: "retweets"
    networks:
      - app-tier

  backend-app:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      PULSAR_IP: pulsar
      PULSAR_PORT: 6650
      PULSAR_TOPIC: "created_objects"
      MEMGRAPH_IP: memgraph-mage
      MEMGRAPH_PORT: "7687"
    depends_on:
      - memgraph-mage
      - pulsar
    networks:
      - app-tier

  frontend-app:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend-app
    networks:
      - app-tier
